### ISSUE TITLE
Crash on Ubuntu 16.04 LTS Firefox

### ISSUE THREAD

**Issue by TheWildBear** [algorithmwatch/datenspende-data-donation#2]
This addon crashes the Firefox on Ubuntu 16.04 LTS. I belive this isn't intended but wasn't tested before.
It crashes on the 5th or 6th time a search was done.

**EDIT: After some testing I found out, _AdblockPlus_ was causing this crash.**

**Comment by davidak** [comment]
>AdblockPlus was causing this crash.

in combination with this extension or independent of it? if it's just ABP, you can close this issue.

**Comment by TheWildBear** [comment]
it crashes, when ABP is enabled. Personally if find that that **is** an issue and should be resolved. A lot of people are using ABP, cause of that this should be resolved.

**Comment by pietsch** [comment]
@TheWildBear: Use uBlock Origin. It's better than Adblock…
